'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.312
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On



'''<summary>
'''ReminderForm class.
'''</summary>
'''<remarks>
'''Auto-generated class.
'''</remarks>
Partial Public Class ReminderForm
    
    '''<summary>
    '''lbItems control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbItems As Global.DevExpress.Web.ASPxEditors.ASPxListBox
    
    '''<summary>
    '''btnDismissAll control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDismissAll As Global.DevExpress.Web.ASPxEditors.ASPxButton
    
    '''<summary>
    '''btnDismiss control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDismiss As Global.DevExpress.Web.ASPxEditors.ASPxButton
    
    '''<summary>
    '''lblClickSnooze control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblClickSnooze As Global.DevExpress.Web.ASPxEditors.ASPxLabel
    
    '''<summary>
    '''cbSnooze control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbSnooze As Global.DevExpress.Web.ASPxEditors.ASPxComboBox
    
    '''<summary>
    '''btnSnooze control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSnooze As Global.DevExpress.Web.ASPxEditors.ASPxButton
End Class
