'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4927
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



Partial Public Class InsertImageForm

    '''<summary>
    '''Panel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel1 As Global.DevExpress.Web.ASPxPanel.ASPxPanel

    '''<summary>
    '''rblFromTheWeb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblFromTheWeb As Global.DevExpress.Web.ASPxEditors.ASPxRadioButton

    '''<summary>
    '''rblFromThisComputer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblFromThisComputer As Global.DevExpress.Web.ASPxEditors.ASPxRadioButton

    '''<summary>
    '''rpInsertImage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rpInsertImage As Global.DevExpress.Web.ASPxHtmlEditor.ASPxHtmlEditorRoundPanel

    '''<summary>
    '''lblImageUrl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblImageUrl As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''txbInsertImageUrl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txbInsertImageUrl As Global.DevExpress.Web.ASPxEditors.ASPxTextBox

    '''<summary>
    '''ckbSaveToServer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ckbSaveToServer As Global.DevExpress.Web.ASPxEditors.ASPxCheckBox

    '''<summary>
    '''lblBrowse control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBrowse As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''uplImage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents uplImage As Global.DevExpress.Web.ASPxHtmlEditor.ASPxHtmlEditorUploadControl

    '''<summary>
    '''ucImagePropertiesForm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ucImagePropertiesForm As Global.ImagePropertiesForm

    '''<summary>
    '''ckbMoreImageOptions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ckbMoreImageOptions As Global.DevExpress.Web.ASPxEditors.ASPxCheckBox

    '''<summary>
    '''btnInsertImage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnInsertImage As Global.DevExpress.Web.ASPxEditors.ASPxButton

    '''<summary>
    '''btnChangeImage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnChangeImage As Global.DevExpress.Web.ASPxEditors.ASPxButton

    '''<summary>
    '''btnInsertImageCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnInsertImageCancel As Global.DevExpress.Web.ASPxEditors.ASPxButton
End Class
